"""Tests for the Constitution Engine."""

from __future__ import annotations

import tempfile
from pathlib import Path

from intelligence.constitution_engine.engine import ConstitutionEngine
from intelligence.constitution_engine.models import ConstitutionRule, ConstitutionSection


def test_constitution_engine_loads_all_sections() -> None:
    """Test that the constitution engine loads all markdown files from the constitution directory."""
    # Use the actual constitution directory that was created
    constitution_dir = Path("constitution")
    
    # Skip test if constitution directory doesn't exist (should exist in our case)
    if not constitution_dir.exists():
        return
    
    engine = ConstitutionEngine(constitution_dir)
    count = engine.index()
    
    # Should have loaded 6 files: architecture, dependencies, testing, security, approval, deployment
    assert count == 6, f"Expected 6 sections, got {count}"
    
    sections = engine.all_sections()
    assert len(sections) == 6
    
    # Check that we have the expected section titles
    titles = {section.title for section in sections}
    expected_titles = {
        "Architecture Rules",
        "Dependency Rules", 
        "Testing Rules",
        "Security Rules",
        "Approval Rules",
        "Deployment Rules"
    }
    assert titles == expected_titles, f"Expected titles {expected_titles}, got {titles}"


def test_constitution_engine_parses_rules_correctly() -> None:
    """Test that the constitution engine correctly parses rules marked with **Rule:**."""
    constitution_dir = Path("constitution")
    if not constitution_dir.exists():
        return
        
    engine = ConstitutionEngine(constitution_dir)
    engine.index()
    
    # Check that each section has rules
    sections = engine.all_sections()
    total_rules = sum(len(section.rules) for section in sections)
    assert total_rules > 0, "Expected at least some rules to be parsed"
    
    # Check a few specific rules we know should be in the files
    all_rules = engine.all_rules()
    rule_texts = [rule.text.lower() for rule in all_rules]
    
    # Check for some representative rules
    assert any("kernel modules must not circularly depend" in text for text in rule_texts)
    assert any("no new external crate may be added" in text for text in rule_texts)
    assert any("all new kernel modules must have unit test coverage" in text for text in rule_texts)
    assert any("all api request bodies must be validated" in text for text in rule_texts)
    assert any("worker diff that modifies files in two or more ownership domains" in text for text in rule_texts)
    assert any("no diff generated by a worker may be deployed to production" in text for text in rule_texts)


def test_constitution_engine_search_functions() -> None:
    """Test that the constitution engine search functions work correctly."""
    constitution_dir = Path("constitution")
    if not constitution_dir.exists():
        return
        
    engine = ConstitutionEngine(constitution_dir)
    engine.index()
    
    # Test search_rules
    kernel_rules = engine.search_rules("kernel")
    assert len(kernel_rules) > 0, "Should find rules containing 'kernel'"
    
    # Test search_text
    security_sections = engine.search_text("security")
    assert len(security_sections) > 0, "Should find sections containing 'security'"
    
    # Test get_section
    architecture_section = engine.get_section("Architecture Rules")
    assert architecture_section is not None, "Should be able to retrieve section by title"
    assert architecture_section.title == "Architecture Rules"
    assert len(architecture_section.rules) > 0, "Architecture section should have rules"
    
    # Test getting non-existent section
    none_section = engine.get_section("Non-existent Section")
    assert none_section is None, "Should return None for non-existent section"


def test_constitution_section_model() -> None:
    """Test the ConstitutionSection and ConstitutionRule models directly."""
    # Test ConstitutionRule
    rule = ConstitutionRule(
        text="Test rule text",
        source_section="Test Section",
        line_number=42
    )
    assert rule.text == "Test rule text"
    assert rule.source_section == "Test Section"
    assert rule.line_number == 42
    
    # Test ConstitutionSection
    section = ConstitutionSection(
        title="Test Section",
        filename="test.md",
        body="# Test Section\n\n**Rule:** Test rule",
        rules=[rule],
        word_count=5
    )
    assert section.title == "Test Section"
    assert section.filename == "test.md"
    assert section.body == "# Test Section\n\n**Rule:** Test rule"
    assert len(section.rules) == 1
    assert section.rules[0] == rule
    assert section.word_count == 5


if __name__ == "__main__":
    test_constitution_engine_loads_all_sections()
    test_constitution_engine_parses_rules_correctly()
    test_constitution_engine_search_functions()
    test_constitution_section_model()
    print("All tests passed!")